function PeaMacros:DefaultMacros_DEATHKNIGHT()
	local macroLib = {
		[250] = { -- Blood
			["PeaMacro01"] = "#showtooltip\n/use [mod:SHIFT,@mouseover,harm,nodead][mod:SHIFT]Chains of Ice;[@mouseover,harm,nodead][]Death's Caress",
			["PeaMacro02"] = "#showtooltip\n/use [mod:SHIFT]Blood Boil;[@mouseover,harm,nodead][]Death Coil",
			["PeaMacro03"] = "#showtooltip\n/use [mod:SHIFT,@pet,nodead]Sacrificial Pact;Heart Strike;\n/use [@pet,nodead] Claw\n/use 13\n/use 14",
			["PeaMacro04"] = "#showtooltip\n/use [mod:SHIFT]Death Strike;Marrowrend;\n/use [@pet,nodead] Claw\n/use 13\n/use 14",
			["PeaMacro05"] = "#showtooltip\n/use [mod:SHIFT] Vampiric Blood;[mod:CTRL]Dancing Rune Weapon;Rune Tap\n/use [@pet,nodead] Claw\n/use 13\n/use 14",
			["PeaMacro06"] = "#showtooltip\n/use [nopet]Raise Dead;[@pet,nodead]Gnaw\n/use [@pet,nodead] Claw\n/use 13\n/use 14",
			["PeaMacro07"] = "#showtooltip\n/use Mind Freeze",
			["PeaMacro08"] = "#showtooltip\n/use [mod:CTRL]Path of Frost;[mod:ALT][@player]Death and Decay",
			["PeaMacro09"] = "#showtooltip\n/use [mod:CTRL,@mouseover,harm,nodead][mod:CTRL]Gorfiend's Grasp;[mod:SHIFT,@mouseover,harm,nodead][mod:SHIFT]Death Grip;[@mouseover,harm,nodead][]Dark Command",
			["PeaMacro10"] = "#showtooltip\n/use [mod:CTRL,talent:5/3]Wraith Walk;[mod:SHIFT]Death's Advance;Bull Rush(Racial)",
			["PeaMacro11"] = "#showtooltip\n/use [mod:CTRL,talent:6/2]Death Pact;[mod:SHIFT,mod:ALT][mod:SHIFT,@player]Anti-Magic Zone;Anti-Magic Shell",
			["PeaMacro12"] = "#showtooltip\n/use [mod:SHIFT]Lichborne;Icebound Fortitude",
		},
		[251] = { -- Frost
			["PeaMacro01"] = "#showtooltip\n/use [mod:SHIFT,@mouseover,harm,nodead][mod:SHIFT]Chains of Ice;[@mouseover,harm,nodead][]Howling Blast",
			["PeaMacro02"] = "#showtooltip\n/use [mod:SHIFT]Death Coil;[@mouseover,harm,nodead][]Frost Strike",
			["PeaMacro03"] = "#showtooltip\n/use [mod:SHIFT,@pet,nodead]Sacrificial Pact;Obliterate;\n/use [@pet,nodead] Claw\n/use 13\n/use 14",
			["PeaMacro04"] = "#showtooltip\n/use [mod:SHIFT]Death Strike;Remorseless Winter;\n/use [@pet,nodead] Claw\n/use 13\n/use 14",
			["PeaMacro05"] = "#showtooltip\n/use ",
			["PeaMacro06"] = "#showtooltip\n/use [mod:SHIFT,talent:3/3]Asphyxiate;[nopet]Raise Dead;[@pet,nodead]Gnaw\n/use [@pet,nodead] Claw\n/use 13\n/use 14",
			["PeaMacro07"] = "#showtooltip\n/use [mod:SHIFT,@pet]Leap;Mind Freeze",
			["PeaMacro08"] = "#showtooltip\n/use [mod:CTRL]Path of Frost;[mod:ALT][@player]Death and Decay",
			["PeaMacro09"] = "#showtooltip\n/use [mod:SHIFT,@mouseover,harm,nodead][mod:SHIFT]Death Grip;Dark Command",
			["PeaMacro10"] = "#showtooltip\n/use [mod:CTRL,talent:5/3]Wraith Walk;[mod:SHIFT]Death's Advance;Bull Rush(Racial)",
			["PeaMacro11"] = "#showtooltip\n/use [mod:CTRL,talent:5/3]Death Pact;[mod:SHIFT,mod:ALT][mod:SHIFT,@player]Anti-Magic Zone;Anti-Magic Shell",
			["PeaMacro12"] = "#showtooltip\n/use [mod:SHIFT]Lichborne;Icebound Fortitude",
		},
		[252] = { --Unholy
			["PeaMacro01"] = "#showtooltip\n/use [mod:ALT,@mouseover,dead,help][mod:ALT]Raise Ally;[mod:SHIFT,talent:2/3]Unholy Blight;[mod:CTRL,@mouseover,harm,nodead][mod:CTRL]Chains of Ice;[@mouseover,harm,nodead][]Outbreak",
			["PeaMacro02"] = "#showtooltip\n/use [mod:SHIFT]Death and Decay;[@mouseover,harm,nodead][@focus,harm,nodead][]Festering Strike\n/use [@pettarget]Claw\n/use 13\n/use 14",
			["PeaMacro03"] = "#showtooltip\n#showtooltip\n/use [mod:SHIFT,@pet,nodead]Sacrificial Pact;Scourge Strike\n/use [@pettarget] Claw\n/use 13\n/use 14",
			["PeaMacro04"] = "#showtooltip\n#showtooltip\n/use [mod:CTRL]Epidemic;[mod:SHIFT,@mouseover,harm,nodead][mod:SHIFT]Death Strike;[@mouseover,harm,nodead][]Death Coil\n/use [@pettarget] Claw\n/use 13\n/use 14",
			["PeaMacro05"] = "#showtooltip\n/use [mod:SHIFT] Apocalypse;Dark Transformation\n/use [@pettarget] Claw\n/use 13\n/use 14",
			["PeaMacro06"] = "#showtooltip\n/cast [mod:SHIFT]Raise Dead;[talent:7/3,@mousover,harm,nodead][talent:7/3,@focus,harm,nodead][talent:7/3]Unholy Assault;[talent:7/2]Summon Gargoyle\n/use 13\n/use 14",
			["PeaMacro07"] = "#showtooltip\n/use [mod:CTRL,@pet]Leap;[mod:SHIFT,talent:3/3,@mouseover,harm,nodead][mod:SHIFT,talent:3/3,@focus,harm,nodead][mod:SHIFT,talent:3/3]Asphyxiate;[@mousover,harm,nodead][@focus,harm,nodead][]Mind Freeze",
			["PeaMacro08"] = "#showtooltip\n/use [mod:SHIFT,@mouseover,harm,nodead][mod:SHIFT]Death Grip;[notalent:4/3]Death and Decay\n/stopmacro [notalent:4/3]\n/use [@focus,harm,nodead][@target]Soul Reaper",
			["PeaMacro09"] = "#showtooltip\n/use [mod:SHIFT,@mouseover,harm,nodead][mod:SHIFT]Death Grip;Dark Command",
			["PeaMacro10"] = "#showtooltip\n/use [mod:CTRL,talent:5/3]Wraith Walk;[mod:SHIFT]Death's Advance;Bull Rush(Racial)",
			["PeaMacro11"] = "#showtooltip\n/use [mod:CTRL,talent:5/3]Death Pact;[mod:SHIFT,mod:ALT][mod:SHIFT,@player]Anti-Magic Zone;Anti-Magic Shell",
			["PeaMacro12"] = "#showtooltip\n/use [mod:SHIFT]Lichborne;Icebound Fortitude",
		},
		[1455] = { -- Unassigned
			["PeaMacro01"] = "#showtooltip\n",
			["PeaMacro02"] = "#showtooltip\n",
			["PeaMacro03"] = "#showtooltip\n",
			["PeaMacro04"] = "#showtooltip\n",
			["PeaMacro05"] = "#showtooltip\n",
			["PeaMacro06"] = "#showtooltip\n",
			["PeaMacro07"] = "#showtooltip\n",
			["PeaMacro08"] = "#showtooltip\n",
			["PeaMacro09"] = "#showtooltip\n",
			["PeaMacro10"] = "#showtooltip\n",
			["PeaMacro11"] = "#showtooltip\n",
			["PeaMacro12"] = "#showtooltip\n",
		},
	}
	return macroLib
end
