function PeaMacros:DefaultMacros_DEMONHUNTER()
	local macroLib = {
		[577] = { -- Havoc
      ["PeaMacro01"] = "#showtooltip\n",
      ["PeaMacro02"] = "#showtooltip\n",
      ["PeaMacro03"] = "#showtooltip\n",
      ["PeaMacro04"] = "#showtooltip\n",
      ["PeaMacro05"] = "#showtooltip\n",
      ["PeaMacro06"] = "#showtooltip\n",
      ["PeaMacro07"] = "#showtooltip\n",
      ["PeaMacro08"] = "#showtooltip\n",
      ["PeaMacro09"] = "#showtooltip\n",
      ["PeaMacro10"] = "#showtooltip\n",
      ["PeaMacro11"] = "#showtooltip\n",
      ["PeaMacro12"] = "#showtooltip\n",
		},
		[581] = { -- Vengeance
      ["PeaMacro01"] = "#showtooltip\n",
      ["PeaMacro02"] = "#showtooltip\n",
      ["PeaMacro03"] = "#showtooltip\n",
      ["PeaMacro04"] = "#showtooltip\n",
      ["PeaMacro05"] = "#showtooltip\n",
      ["PeaMacro06"] = "#showtooltip\n",
      ["PeaMacro07"] = "#showtooltip\n",
      ["PeaMacro08"] = "#showtooltip\n",
      ["PeaMacro09"] = "#showtooltip\n",
      ["PeaMacro10"] = "#showtooltip\n",
      ["PeaMacro11"] = "#showtooltip\n",
      ["PeaMacro12"] = "#showtooltip\n",
		},
		[1456] = { -- Unassigned
			["PeaMacro01"] = "#showtooltip\n",
			["PeaMacro02"] = "#showtooltip\n",
			["PeaMacro03"] = "#showtooltip\n",
			["PeaMacro04"] = "#showtooltip\n",
			["PeaMacro05"] = "#showtooltip\n",
			["PeaMacro06"] = "#showtooltip\n",
			["PeaMacro07"] = "#showtooltip\n",
			["PeaMacro08"] = "#showtooltip\n",
			["PeaMacro09"] = "#showtooltip\n",
			["PeaMacro10"] = "#showtooltip\n",
			["PeaMacro11"] = "#showtooltip\n",
			["PeaMacro12"] = "#showtooltip\n",
		},
	}
	return macroLib
end
