function PeaMacros:DefaultMacros_DRUID()
	local macroLib = {
		[102] = { -- Balance
      ["PeaMacro01"] = "#showtooltip\n",
      ["PeaMacro02"] = "#showtooltip\n",
      ["PeaMacro03"] = "#showtooltip\n",
      ["PeaMacro04"] = "#showtooltip\n",
      ["PeaMacro05"] = "#showtooltip\n",
      ["PeaMacro06"] = "#showtooltip\n",
      ["PeaMacro07"] = "#showtooltip\n",
      ["PeaMacro08"] = "#showtooltip\n",
      ["PeaMacro09"] = "#showtooltip\n",
      ["PeaMacro10"] = "#showtooltip\n",
      ["PeaMacro11"] = "#showtooltip\n",
      ["PeaMacro12"] = "#showtooltip\n",
		},
		[103] = { -- Feral
      ["PeaMacro01"] = "#showtooltip\n",
      ["PeaMacro02"] = "#showtooltip\n",
      ["PeaMacro03"] = "#showtooltip\n",
      ["PeaMacro04"] = "#showtooltip\n",
      ["PeaMacro05"] = "#showtooltip\n",
      ["PeaMacro06"] = "#showtooltip\n",
      ["PeaMacro07"] = "#showtooltip\n",
      ["PeaMacro08"] = "#showtooltip\n",
      ["PeaMacro09"] = "#showtooltip\n",
      ["PeaMacro10"] = "#showtooltip\n",
      ["PeaMacro11"] = "#showtooltip\n",
      ["PeaMacro12"] = "#showtooltip\n",
		},
		[104] = { --Guardian
      ["PeaMacro01"] = "#showtooltip\n",
      ["PeaMacro02"] = "#showtooltip\n",
      ["PeaMacro03"] = "#showtooltip\n",
      ["PeaMacro04"] = "#showtooltip\n",
      ["PeaMacro05"] = "#showtooltip\n",
      ["PeaMacro06"] = "#showtooltip\n",
      ["PeaMacro07"] = "#showtooltip\n",
      ["PeaMacro08"] = "#showtooltip\n",
      ["PeaMacro09"] = "#showtooltip\n",
      ["PeaMacro10"] = "#showtooltip\n",
      ["PeaMacro11"] = "#showtooltip\n",
      ["PeaMacro12"] = "#showtooltip\n",
		},
		[105] = { --Restoration
      ["PeaMacro01"] = "#showtooltip\n",
      ["PeaMacro02"] = "#showtooltip\n",
      ["PeaMacro03"] = "#showtooltip\n",
      ["PeaMacro04"] = "#showtooltip\n",
      ["PeaMacro05"] = "#showtooltip\n",
      ["PeaMacro06"] = "#showtooltip\n",
      ["PeaMacro07"] = "#showtooltip\n",
      ["PeaMacro08"] = "#showtooltip\n",
      ["PeaMacro09"] = "#showtooltip\n",
      ["PeaMacro10"] = "#showtooltip\n",
      ["PeaMacro11"] = "#showtooltip\n",
      ["PeaMacro12"] = "#showtooltip\n",
		},
		[1447] = { -- Unassigned
			["PeaMacro01"] = "#showtooltip\n",
			["PeaMacro02"] = "#showtooltip\n",
			["PeaMacro03"] = "#showtooltip\n",
			["PeaMacro04"] = "#showtooltip\n",
			["PeaMacro05"] = "#showtooltip\n",
			["PeaMacro06"] = "#showtooltip\n",
			["PeaMacro07"] = "#showtooltip\n",
			["PeaMacro08"] = "#showtooltip\n",
			["PeaMacro09"] = "#showtooltip\n",
			["PeaMacro10"] = "#showtooltip\n",
			["PeaMacro11"] = "#showtooltip\n",
			["PeaMacro12"] = "#showtooltip\n",
		},
	}
	return macroLib
end
