function PeaMacros:DefaultMacros_HUNTER()
	local macroLib = {
		[253] = { -- Beast Mastery
      ["PeaMacro01"] = "#showtooltip\n/use [mod:CTRL,nomod:ALT,@player][mod:CTRL,mod:ALT]Freezing Trap;[mod:SHIFT,@mouseover,help,nodead][mod:SHIFT,@focus,help,nodead][mod:SHIFT,@pet,exists,nodead][mod:SHIFT]Misdirection;[@mouseover,harm,nodead][]Hunter's Mark",
      ["PeaMacro02"] = "#showtooltip\n/use [mod:CTRL,nomod:ALT,@player][mod:CTRL,mod:ALT]Tar Trap;[mod:SHIFT]Barrage;Cobra Shot\n/use [@pettarget]Smack\n/use [@pettarget]Bite\n/use [@pettarget]Claw",
      ["PeaMacro03"] = "#showtooltip\n/use [mod:SHIFT,@mouseover,harm,nodead][mod:SHIFT]Multi-Shot;[mod:CTRL,@player][mod:CTRL,mod:ALT]Flare;[@mouseover,harm,nodead][@focus,harm,nodead][@target]Barbed Shot\n/use [@pettarget]Smack\n/use [@pettarget]Bite\n/use [@pettarget]Claw",
      ["PeaMacro04"] = "#showtooltip\n/petattack[nomod,@mouseover,harm,nodead][nomod,@focus,harm,nodead][nomod,@target]\n/use [mod:SHIFT]A Murder of Crows;[@mouseover,harm,nodead][@focus,harm,nodead][@target]Kill Command",
      ["PeaMacro05"] = "#showtooltip\n/use [mod:SHIFT]Aspect of the Wild; Bestial Wrath\n/use 13\n/use 14",
      ["PeaMacro06"] = "#showtooltip\n\/use [mod:SHIFT]Disengage;[mod:CTRL,@mouseover,harm,nodead][@mod:CTRL]Wing Clip;[@mouseover,harm,nodead][@focus,harm,nodead][]Concussive Shot",
      ["PeaMacro07"] = "#showtooltip\n/use [mod:CTRL,@mouseover,harm,nodead][mod:CTRL,@focus,harm,nodead][mod:CTRL]Tranquilizing Shot;[mod:SHIFT,@mouseover,harm,nodead][mod:SHIFT,@focus,harm,nodead][mod:SHIFT]Intimidation;[@mouseover,harm,nodead][@focus,harm,nodead][]Counter Shot",
      ["PeaMacro08"] = "#showtooltip\n/petattack[@mouseover,harm,nodead][@focus,harm,nodead][@target]\n/use [@mouseover,harm,nodead][@focus,harm,nodead][@target]Kill Shot",
      ["PeaMacro09"] = "#showtooltip\n/use Aspect of the Cheetah",
      ["PeaMacro10"] = "#showtooltip\n-- Covenant abilities",
      ["PeaMacro11"] = "#showtooltip\n/use [mod:ALT,@player]Spirit Mend(Exotic Ability);[mod:SHIFT,@pet,exists,nodead]Mend Pet;[mod:SHIFT,@pet,exists,dead]Revive Pet;[mod:SHIFT,nopet]Call Pet 1;Exhilaration",
      ["PeaMacro12"] = "#showtooltip\n/use Aspect of the Turtle\n/stopmacro [mod:ALT]\n/cancelaura Aspect of the Turtle",
		},
		[254] = { -- Marksmanship
			["PeaMacro01"] = "#showtooltip\n/use [mod:CTRL,nomod:ALT,@player][mod:CTRL,mod:ALT]Freezing Trap;[mod:SHIFT,@mouseover,help,nodead][mod:SHIFT,@focus,help,nodead][mod:SHIFT,@pet,exists,nodead][mod:SHIFT]Misdirection;[@mouseover,harm,nodead][]Rapid Fire",
			["PeaMacro02"] = "#showtooltip\n/use [mod:CTRL,nomod:ALT,@player][mod:CTRL,mod:ALT]Tar Trap;[mod:SHIFT]Volley;Steady Shot\n/use [@pettarget]Smack\n/use [@pettarget]Bite\n/use [@pettarget]Claw",
			["PeaMacro03"] = "#showtooltip\n/use [mod:SHIFT,@mouseover,harm,nodead][mod:SHIFT]Multi-Shot;[mod:CTRL,@player][mod:CTRL,mod:ALT]Flare;[@mouseover,harm,nodead][@focus,harm,nodead][@target]Arcane Shot\n/use [@pettarget]Smack\n/use [@pettarget]Bite\n/use [@pettarget]Claw",
			["PeaMacro04"] = "#showtooltip\n/petattack[nomod,@mouseover,harm,nodead][nomod,@focus,harm,nodead][nomod,@target]\n/use [mod:SHIFT]Explosive Shot;[@mouseover,harm,nodead][@focus,harm,nodead][@target]Aimed Shot",
			["PeaMacro05"] = "#showtooltip\n/use [mod:SHIFT]Double Tap;Trueshot\n/use 13\n/use 14",
			["PeaMacro06"] = "#showtooltip\n\/use [mod:SHIFT]Disengage;[mod:CTRL,@mouseover,harm,nodead][@mod:CTRL]Wing Clip;[@mouseover,harm,nodead][@focus,harm,nodead][]Concussive Shot",
			["PeaMacro07"] = "#showtooltip\n/use [mod:CTRL,@mouseover,harm,nodead][mod:CTRL,@focus,harm,nodead][mod:CTRL]Tranquilizing Shot;[mod:SHIFT,@mouseover,harm,nodead][mod:SHIFT,@focus,harm,nodead][mod:SHIFT]Intimidation;[@mouseover,harm,nodead][@focus,harm,nodead][]Counter Shot",
			["PeaMacro08"] = "#showtooltip\n/petattack[@mouseover,harm,nodead][@focus,harm,nodead][@target]\n/use [@mouseover,harm,nodead][@focus,harm,nodead][@target]Kill Shot",
			["PeaMacro09"] = "#showtooltip\n/use Aspect of the Cheetah",
			["PeaMacro10"] = "#showtooltip\n-- Covenant abilities",
			["PeaMacro11"] = "#showtooltip\n/use [mod:SHIFT,@pet,exists,nodead]Mend Pet;[mod:SHIFT,@pet,exists,dead]Revive Pet;[mod:SHIFT,nopet]Call Pet 1;Exhilaration",
			["PeaMacro12"] = "#showtooltip\n/use Aspect of the Turtle\n/stopmacro [mod:ALT]\n/cancelaura Aspect of the Turtle",
		},
		[255] = { --Survival
			["PeaMacro01"] = "#showtooltip\n/use [mod:CTRL,nomod:ALT,@player][mod:CTRL,mod:ALT]Freezing Trap;[mod:SHIFT,@mouseover,help,nodead][mod:SHIFT,@focus,help,nodead][mod:SHIFT,@pet,exists,nodead][mod:SHIFT]Misdirection;[@mouseover,harm,nodead][]",
			["PeaMacro02"] = "#showtooltip\n/use [mod:CTRL,nomod:ALT,@player][mod:CTRL,mod:ALT]Tar Trap;[mod:SHIFT]Barrage;Kill Command\n/use [@pettarget]Smack\n/use [@pettarget]Bite\n/use [@pettarget]Claw",
			["PeaMacro03"] = "#showtooltip\n/use [mod:SHIFT,@mouseover,harm,nodead][mod:SHIFT]Carve;[mod:CTRL,@player][mod:CTRL,mod:ALT]Flare;[@mouseover,harm,nodead][@focus,harm,nodead][@target]Raptor Strike\n/use [@pettarget]Smack\n/use [@pettarget]Bite\n/use [@pettarget]Claw",
			["PeaMacro04"] = "#showtooltip\n/petattack[nomod,@mouseover,harm,nodead][nomod,@focus,harm,nodead][nomod,@target]\n/use [mod:SHIFT]Serpent Sting;[@mouseover,harm,nodead][@focus,harm,nodead][@target]Wildfire Bomb",
			["PeaMacro05"] = "#showtooltip\n/use [mod:SHIFT]Aspect of the Wild;Coordinated Assault\n/use 13\n/use 14",
			["PeaMacro06"] = "#showtooltip\n\/use [mod:SHIFT]Disengage;[mod:CTRL,@mouseover,harm,nodead][@mod:CTRL]Wing Clip;[@mouseover,harm,nodead][@focus,harm,nodead][]Concussive Shot",
			["PeaMacro07"] = "#showtooltip\n/use [mod:CTRL,@mouseover,harm,nodead][mod:CTRL,@focus,harm,nodead][mod:CTRL]Tranquilizing Shot;[mod:SHIFT,@mouseover,harm,nodead][mod:SHIFT,@focus,harm,nodead][mod:SHIFT]Intimidation;[@mouseover,harm,nodead][@focus,harm,nodead][]Counter Shot",
			["PeaMacro08"] = "#showtooltip\n/petattack[@mouseover,harm,nodead][@focus,harm,nodead][@target]\n/use [@mouseover,harm,nodead][@focus,harm,nodead][@target]Kill Shot",
			["PeaMacro09"] = "#showtooltip\n/use Aspect of the Cheetah",
			["PeaMacro10"] = "#showtooltip\n-- Covenant abilities",
			["PeaMacro11"] = "#showtooltip\n/use [mod:ALT,@player]Spirit Mend(Exotic Ability);[mod:SHIFT,@pet,exists,nodead]Mend Pet;[mod:SHIFT,@pet,exists,dead]Revive Pet;[mod:SHIFT,nopet]Call Pet 1;Exhilaration",
			["PeaMacro12"] = "#showtooltip\n/use Aspect of the Turtle\n/stopmacro [mod:ALT]\n/cancelaura Aspect of the Turtle",
		},
		[1448] = { -- Unassigned
			["PeaMacro01"] = "#showtooltip\n",
			["PeaMacro02"] = "#showtooltip\n",
			["PeaMacro03"] = "#showtooltip\n",
			["PeaMacro04"] = "#showtooltip\n",
			["PeaMacro05"] = "#showtooltip\n",
			["PeaMacro06"] = "#showtooltip\n",
			["PeaMacro07"] = "#showtooltip\n",
			["PeaMacro08"] = "#showtooltip\n",
			["PeaMacro09"] = "#showtooltip\n",
			["PeaMacro10"] = "#showtooltip\n",
			["PeaMacro11"] = "#showtooltip\n",
			["PeaMacro12"] = "#showtooltip\n",
		},
	}
	return macroLib
end
