function PeaMacros:DefaultMacros_HUNTER()
	local macroLib = {
		[253] = { -- Beast Mastery
      ["PeaMacro01"] = "#showtooltip\n",
      ["PeaMacro02"] = "#showtooltip\n",
      ["PeaMacro03"] = "#showtooltip\n",
      ["PeaMacro04"] = "#showtooltip\n",
      ["PeaMacro05"] = "#showtooltip\n",
      ["PeaMacro06"] = "#showtooltip\n",
      ["PeaMacro07"] = "#showtooltip\n",
      ["PeaMacro08"] = "#showtooltip\n",
      ["PeaMacro09"] = "#showtooltip\n",
      ["PeaMacro10"] = "#showtooltip\n",
      ["PeaMacro11"] = "#showtooltip\n",
      ["PeaMacro12"] = "#showtooltip\n",
		},
		[254] = { -- Marksmanship
      ["PeaMacro01"] = "#showtooltip\n",
      ["PeaMacro02"] = "#showtooltip\n",
      ["PeaMacro03"] = "#showtooltip\n",
      ["PeaMacro04"] = "#showtooltip\n",
      ["PeaMacro05"] = "#showtooltip\n",
      ["PeaMacro06"] = "#showtooltip\n",
      ["PeaMacro07"] = "#showtooltip\n",
      ["PeaMacro08"] = "#showtooltip\n",
      ["PeaMacro09"] = "#showtooltip\n",
      ["PeaMacro10"] = "#showtooltip\n",
      ["PeaMacro11"] = "#showtooltip\n",
      ["PeaMacro12"] = "#showtooltip\n",
		},
		[255] = { --Survival
      ["PeaMacro01"] = "#showtooltip\n",
      ["PeaMacro02"] = "#showtooltip\n",
      ["PeaMacro03"] = "#showtooltip\n",
      ["PeaMacro04"] = "#showtooltip\n",
      ["PeaMacro05"] = "#showtooltip\n",
      ["PeaMacro06"] = "#showtooltip\n",
      ["PeaMacro07"] = "#showtooltip\n",
      ["PeaMacro08"] = "#showtooltip\n",
      ["PeaMacro09"] = "#showtooltip\n",
      ["PeaMacro10"] = "#showtooltip\n",
      ["PeaMacro11"] = "#showtooltip\n",
      ["PeaMacro12"] = "#showtooltip\n",
		},
		[1448] = { -- Unassigned
			["PeaMacro01"] = "#showtooltip\n",
			["PeaMacro02"] = "#showtooltip\n",
			["PeaMacro03"] = "#showtooltip\n",
			["PeaMacro04"] = "#showtooltip\n",
			["PeaMacro05"] = "#showtooltip\n",
			["PeaMacro06"] = "#showtooltip\n",
			["PeaMacro07"] = "#showtooltip\n",
			["PeaMacro08"] = "#showtooltip\n",
			["PeaMacro09"] = "#showtooltip\n",
			["PeaMacro10"] = "#showtooltip\n",
			["PeaMacro11"] = "#showtooltip\n",
			["PeaMacro12"] = "#showtooltip\n",
		},
	}
	return macroLib
end
