function PeaMacros:DefaultMacros_MAGE()
	local macroLib = {
		[62] = { -- Arcane
      ["PeaMacro01"] = "#showtooltip\n/use [mod:CTRL,@mouseover,harm,nodead][mod:CTRL,@focus,harm,nodead][mod:CTRL]Polymorph;[mod:ALT]Conjure Mana Gem;[mod:SHIFT]Evocation;Mana Gem",
      ["PeaMacro02"] = "#showtooltip\n/use [mod:SHIFT]Arcane Explosion;[@mouseover,harm,nodead][]Arcane Blast",
      ["PeaMacro03"] = "#showtooltip\n/use Arcane Missiles",
      ["PeaMacro04"] = "#showtooltip\n/use [mod:SHIFT]Touch of the Magi;Arcane Barrage",
      ["PeaMacro05"] = "#showtooltip\n/use Arcane Power",
      ["PeaMacro06"] = "#showtooltip\n/use [mod:CTRL] Slow; [mod:SHIFT]Arcane Pulse;Frost Nova",
      ["PeaMacro07"] = "#showtooltip\n/use [@mouseover,harm,nodead][@focus,harm,nodead][]Counterspell",
      ["PeaMacro08"] = "#showtooltip\n/use Alter Time",
      ["PeaMacro09"] = "#showtooltip\n/use Arcane Intellect",
      ["PeaMacro10"] = "#showtooltip\n/use Blink",
      ["PeaMacro11"] = "#showtooltip\n",
      ["PeaMacro12"] = "#showtooltip\n/use [mod:SHIFT]Ice Block;Prismatic Barrier",
		},
		[63] = { -- Fire
      ["PeaMacro01"] = "#showtooltip\n",
      ["PeaMacro02"] = "#showtooltip\n",
      ["PeaMacro03"] = "#showtooltip\n",
      ["PeaMacro04"] = "#showtooltip\n",
      ["PeaMacro05"] = "#showtooltip\n",
      ["PeaMacro06"] = "#showtooltip\n",
      ["PeaMacro07"] = "#showtooltip\n",
      ["PeaMacro08"] = "#showtooltip\n",
      ["PeaMacro09"] = "#showtooltip\n",
      ["PeaMacro10"] = "#showtooltip\n",
      ["PeaMacro11"] = "#showtooltip\n",
      ["PeaMacro12"] = "#showtooltip\n",
		},
		[64] = { --Frost
      ["PeaMacro01"] = "#showtooltip\n",
      ["PeaMacro02"] = "#showtooltip\n",
      ["PeaMacro03"] = "#showtooltip\n",
      ["PeaMacro04"] = "#showtooltip\n",
      ["PeaMacro05"] = "#showtooltip\n",
      ["PeaMacro06"] = "#showtooltip\n",
      ["PeaMacro07"] = "#showtooltip\n",
      ["PeaMacro08"] = "#showtooltip\n",
      ["PeaMacro09"] = "#showtooltip\n",
      ["PeaMacro10"] = "#showtooltip\n",
      ["PeaMacro11"] = "#showtooltip\n",
      ["PeaMacro12"] = "#showtooltip\n",
		},
		[1449] = { -- Unassigned
			["PeaMacro01"] = "#showtooltip\n",
			["PeaMacro02"] = "#showtooltip\n",
			["PeaMacro03"] = "#showtooltip\n",
			["PeaMacro04"] = "#showtooltip\n",
			["PeaMacro05"] = "#showtooltip\n",
			["PeaMacro06"] = "#showtooltip\n",
			["PeaMacro07"] = "#showtooltip\n",
			["PeaMacro08"] = "#showtooltip\n",
			["PeaMacro09"] = "#showtooltip\n",
			["PeaMacro10"] = "#showtooltip\n",
			["PeaMacro11"] = "#showtooltip\n",
			["PeaMacro12"] = "#showtooltip\n",
		},
	}
	return macroLib
end
