function PeaMacros:DefaultMacros_MAGE()
	local macroLib = {
		[62] = { -- Arcane
      ["PeaMacro01"] = "#showtooltip\n",
      ["PeaMacro02"] = "#showtooltip\n",
      ["PeaMacro03"] = "#showtooltip\n",
      ["PeaMacro04"] = "#showtooltip\n",
      ["PeaMacro05"] = "#showtooltip\n",
      ["PeaMacro06"] = "#showtooltip\n",
      ["PeaMacro07"] = "#showtooltip\n",
      ["PeaMacro08"] = "#showtooltip\n",
      ["PeaMacro09"] = "#showtooltip\n",
      ["PeaMacro010"] = "#showtooltip\n",
      ["PeaMacro011"] = "#showtooltip\n",
      ["PeaMacro012"] = "#showtooltip\n",
		},
		[63] = { -- Fire
      ["PeaMacro01"] = "#showtooltip\n",
      ["PeaMacro02"] = "#showtooltip\n",
      ["PeaMacro03"] = "#showtooltip\n",
      ["PeaMacro04"] = "#showtooltip\n",
      ["PeaMacro05"] = "#showtooltip\n",
      ["PeaMacro06"] = "#showtooltip\n",
      ["PeaMacro07"] = "#showtooltip\n",
      ["PeaMacro08"] = "#showtooltip\n",
      ["PeaMacro09"] = "#showtooltip\n",
      ["PeaMacro010"] = "#showtooltip\n",
      ["PeaMacro011"] = "#showtooltip\n",
      ["PeaMacro012"] = "#showtooltip\n",
		},
		[64] = { --Frost
      ["PeaMacro01"] = "#showtooltip\n",
      ["PeaMacro02"] = "#showtooltip\n",
      ["PeaMacro03"] = "#showtooltip\n",
      ["PeaMacro04"] = "#showtooltip\n",
      ["PeaMacro05"] = "#showtooltip\n",
      ["PeaMacro06"] = "#showtooltip\n",
      ["PeaMacro07"] = "#showtooltip\n",
      ["PeaMacro08"] = "#showtooltip\n",
      ["PeaMacro09"] = "#showtooltip\n",
      ["PeaMacro010"] = "#showtooltip\n",
      ["PeaMacro011"] = "#showtooltip\n",
      ["PeaMacro012"] = "#showtooltip\n",
		},
		[1449] = { -- Unassigned
			["PeaMacro01"] = "#showtooltip\n",
			["PeaMacro02"] = "#showtooltip\n",
			["PeaMacro03"] = "#showtooltip\n",
			["PeaMacro04"] = "#showtooltip\n",
			["PeaMacro05"] = "#showtooltip\n",
			["PeaMacro06"] = "#showtooltip\n",
			["PeaMacro07"] = "#showtooltip\n",
			["PeaMacro08"] = "#showtooltip\n",
			["PeaMacro09"] = "#showtooltip\n",
			["PeaMacro010"] = "#showtooltip\n",
			["PeaMacro011"] = "#showtooltip\n",
			["PeaMacro012"] = "#showtooltip\n",
		},
	}
	return macroLib
end
