function PeaMacros:DefaultMacros_PALADIN()
	local macroLib = {
		[65] = { -- Holy
      ["PeaMacro01"] = "#showtooltip\n",
      ["PeaMacro02"] = "#showtooltip\n",
      ["PeaMacro03"] = "#showtooltip\n",
      ["PeaMacro04"] = "#showtooltip\n",
      ["PeaMacro05"] = "#showtooltip\n",
      ["PeaMacro06"] = "#showtooltip\n",
      ["PeaMacro07"] = "#showtooltip\n",
      ["PeaMacro08"] = "#showtooltip\n",
      ["PeaMacro09"] = "#showtooltip\n",
      ["PeaMacro10"] = "#showtooltip\n",
      ["PeaMacro11"] = "#showtooltip\n",
      ["PeaMacro12"] = "#showtooltip\n",
		},
		[66] = { -- Protection
			["PeaMacro01"] = "#showtooltip\n/cast [@mouseover,harm,nodead][] Avenger's Shield",
			["PeaMacro02"] = "#showtooltip\n/cast  [spec:3,mod:SHIFT,@mouseover,harm,nodead][spec:3,mod:SHIFT,@focus,harm,nodead][spec:3,mod:SHIFT]Blade of Justice; [@mouseover,harm,nodead][@focus,harm,nodead][] Crusader Strike",
			["PeaMacro03"] = "#showtooltip\n/cast [@mouseover,harm,nodead][@focus,harm,nodead][] Judgment",
			["PeaMacro04"] = "#showtooltip\n/use [mod:SHIFT]Seraphim;[@mouseover,harm,nodead][@focus,harm,nodead][] Shield of the Righteous\n/use 13\n/use 14",
			["PeaMacro05"] = "#showtooltip\n/cast [spec:3,mod:SHIFT]Shield of Vengeance;[spec:2,mod:SHIFT]Guardian of Ancient Kings;Consecration",
			["PeaMacro06"] = "#showtooltip\n/cast [@mouseover,harm,nodead][] Hammer of Justice",
			["PeaMacro07"] = "#showtooltip\n/use [mod:SHIFT,@mouseover,help,nodead][mod:SHIFT,@focus,help,nodead][mod:SHIFT]Cleanse Toxins;[@mouseover,harm,nodead][@focus,harm,nodead][]Rebuke\n",
			["PeaMacro08"] = "#showtooltip\n/use [mod:SHIFT]Avenging Wrath; [@mouseover,harm,nodead][@focus,harm,nodead][]Hammer of Wrath",
			["PeaMacro09"] = "#showtooltip\n/cast [@mouseover,harm,nodead][] Hand of Reckoning",
			["PeaMacro10"] = "#showtooltip\n/cast [mod:shift] Pterrordax Swoop(Racial); Divine Steed",
			["PeaMacro11"] = "#showtooltip\n/cast [mod:SHIFT,@mouseover,dead][mod:SHIFT]Word of Glory; [mod:ALT]Regeneratin'(Racial); [mod:CTRL,@mouseover,help,nodead][mod:CTRL]Lay on Hands; [@mouseover,help,nodead][]Flash of Light\n",
			["PeaMacro12"] = "#showtooltip\n/cast [mod:ctl,@mouseover,help,nodead][mod:ctrl] Blessing of Freedom; [mod:shift,@mouseover,help,nodead][mod:shift] Blessing of Protection; [mod:alt] Divine Shield; Ardent Defender",
		},
		[70] = { --Retribution
      ["PeaMacro01"] = "#showtooltip\n",
      ["PeaMacro02"] = "#showtooltip\n",
      ["PeaMacro03"] = "#showtooltip\n",
      ["PeaMacro04"] = "#showtooltip\n",
      ["PeaMacro05"] = "#showtooltip\n",
      ["PeaMacro06"] = "#showtooltip\n",
      ["PeaMacro07"] = "#showtooltip\n",
      ["PeaMacro08"] = "#showtooltip\n",
      ["PeaMacro09"] = "#showtooltip\n",
      ["PeaMacro10"] = "#showtooltip\n",
      ["PeaMacro11"] = "#showtooltip\n",
      ["PeaMacro12"] = "#showtooltip\n",
		},
		[1451] = { -- Unassigned
			["PeaMacro01"] = "#showtooltip\n",
			["PeaMacro02"] = "#showtooltip\n",
			["PeaMacro03"] = "#showtooltip\n",
			["PeaMacro04"] = "#showtooltip\n",
			["PeaMacro05"] = "#showtooltip\n",
			["PeaMacro06"] = "#showtooltip\n",
			["PeaMacro07"] = "#showtooltip\n",
			["PeaMacro08"] = "#showtooltip\n",
			["PeaMacro09"] = "#showtooltip\n",
			["PeaMacro10"] = "#showtooltip\n",
			["PeaMacro11"] = "#showtooltip\n",
			["PeaMacro12"] = "#showtooltip\n",
		},
	}
	return macroLib
end
