function PeaMacros:DefaultMacros_PALADIN()
	local macroLib = {
		[65] = { -- Holy
      ["PeaMacro01"] = "#showtooltip\n/use [mod:CTRL,@focus,help,nodead][mod:CTRL]Beacon of Light;[mod:SHIFT,@mouseover,help,nodead][mod:SHIFT]Flash of Light;[@mouseover,help,nodead][]Holy Light",
      ["PeaMacro02"] = "#showtooltip\n/use [mod:SHIFT,@mouseover,harm,nodead][mod:SHIFT]Light of Dawn;[@mouseover,help,nodead][]Holy Shock",
      ["PeaMacro03"] = "#showtooltip\n/use [mod:SHIFT,@mouseover,harm,nodead][mod:SHIFT]Divine Toll;[@mouseover,harm,nodead][] Crusader Strike",
      ["PeaMacro04"] = "#showtooltip\n/use [mod:SHIFT,talent:5/3]Seraphim;[mod:SHIFT,@mouseover,help,nodead][mod:SHIFT]Word of Glory;[@mouseover,harm,nodead][]Shield of the Righteous",
      ["PeaMacro05"] = "#showtooltip\n/use [mod:CTRL,talent:5/2]Holy Avenger;[mod:SHIFT]Aura Mastery;[talent:4/3]Rule of Law;Avenging Wrath",
      ["PeaMacro06"] = "#showtooltip\n/use [mod:SHIFT,@mouseover,harm,nodead][mod:SHIFT]Turn Evil;[@mouseover,harm,nodead][]Hammer of Justice",
      ["PeaMacro07"] = "#showtooltip\n/use [@mouseover,help,nodead][]Cleanse",
      ["PeaMacro08"] = "#showtooltip\n/use [mod:SHIFT,talent:4/3]Avenging Wrath; [@mouseover,harm,nodead][@focus,harm,nodead][]Hammer of Wrath",
      ["PeaMacro09"] = "#showtooltip\n/use [@mouseover,help,nodead][]Light of the Martyr",
      ["PeaMacro10"] = "#showtooltip\n/cast [mod:shift] Pterrordax Swoop(Racial); Divine Steed",
      ["PeaMacro11"] = "#showtooltip\n/cast [mod:ALT]Regeneratin'(Racial);[mod:CTRL]Summon Steward;[mod:@mouseover,help,nodead][]Lay on Hands",
      ["PeaMacro12"] = "#showtooltip\n/use [mod:CTRL,@mouseover,help,nodead][mod:CTRL]Blessing of Freedom;[mod:SHIFT,@mouseover,help,nodead][mod:SHIFT] Blessing of Protection; [mod:ALT] Divine Shield; Divine Protection",
		},
		[66] = { -- Protection
			["PeaMacro01"] = "#showtooltip\n/use [@mouseover,harm,nodead][] Avenger's Shield",
			["PeaMacro02"] = "#showtooltip\n/use [mod:SHIFT,@mouseover,harm,nodead][mod:SHIFT,@focus,harm,nodead][mod:SHIFT]Blade of Justice; [@mouseover,harm,nodead][@focus,harm,nodead][] Crusader Strike",
			["PeaMacro03"] = "#showtooltip\n/use [@mouseover,harm,nodead][@focus,harm,nodead][] Judgment",
			["PeaMacro04"] = "#showtooltip\n/use [mod:SHIFT]Seraphim;[@mouseover,harm,nodead][@focus,harm,nodead][] Shield of the Righteous\n/use 13\n/use 14",
			["PeaMacro05"] = "#showtooltip\n/use [mod:SHIFT]Shield of Vengeance;Consecration",
			["PeaMacro06"] = "#showtooltip\n/use [@mouseover,harm,nodead][] Hammer of Justice",
			["PeaMacro07"] = "#showtooltip\n/use [mod:SHIFT,@mouseover,help,nodead][mod:SHIFT,@focus,help,nodead][mod:SHIFT]Cleanse Toxins;[@mouseover,harm,nodead][@focus,harm,nodead][]Rebuke\n",
			["PeaMacro08"] = "#showtooltip\n/use [mod:SHIFT]Avenging Wrath; [@mouseover,harm,nodead][@focus,harm,nodead][]Hammer of Wrath",
			["PeaMacro09"] = "#showtooltip\n/use [@mouseover,harm,nodead][] Hand of Reckoning",
			["PeaMacro10"] = "#showtooltip\n/use [mod:SHIFT] Pterrordax Swoop(Racial); Divine Steed",
			["PeaMacro11"] = "#showtooltip\n/use [mod:SHIFT,@mouseover,dead][mod:SHIFT]Word of Glory;[mod:ALT]Regeneratin'(Racial);[mod:CTRL,@mouseover,help,nodead][mod:CTRL]Lay on Hands;[@mouseover,help,nodead][]Flash of Light\n",
			["PeaMacro12"] = "#showtooltip\n/use [mod:CTRL,@mouseover,help,nodead][mod:CTRL]Blessing of Freedom;[mod:SHIFT,@mouseover,help,nodead][mod:SHIFT]Blessing of Protection;[mod:ALT]Divine Shield;Ardent Defender",
		},
		[70] = { --Retribution
      ["PeaMacro01"] = "#showtooltip\n",
      ["PeaMacro02"] = "#showtooltip\n",
      ["PeaMacro03"] = "#showtooltip\n",
      ["PeaMacro04"] = "#showtooltip\n",
      ["PeaMacro05"] = "#showtooltip\n",
      ["PeaMacro06"] = "#showtooltip\n",
      ["PeaMacro07"] = "#showtooltip\n",
      ["PeaMacro08"] = "#showtooltip\n",
      ["PeaMacro09"] = "#showtooltip\n",
      ["PeaMacro10"] = "#showtooltip\n",
      ["PeaMacro11"] = "#showtooltip\n",
      ["PeaMacro12"] = "#showtooltip\n",
		},
		[1451] = { -- Unassigned
			["PeaMacro01"] = "#showtooltip\n",
			["PeaMacro02"] = "#showtooltip\n",
			["PeaMacro03"] = "#showtooltip\n",
			["PeaMacro04"] = "#showtooltip\n",
			["PeaMacro05"] = "#showtooltip\n",
			["PeaMacro06"] = "#showtooltip\n",
			["PeaMacro07"] = "#showtooltip\n",
			["PeaMacro08"] = "#showtooltip\n",
			["PeaMacro09"] = "#showtooltip\n",
			["PeaMacro10"] = "#showtooltip\n",
			["PeaMacro11"] = "#showtooltip\n",
			["PeaMacro12"] = "#showtooltip\n",
		},
	}
	return macroLib
end
