function PeaMacros:DefaultMacros_WARLOCK()
	local macroLib = {
		[265] = { -- Affliction
			["PeaMacro06"] = "#showtooltip\n/use [combat]Fel Domination\n/stopcasting [combat]\n/use [mod:CTRL,mod:SHIFT]Summon Succubus;[mod:CTRL]Summon Felhunter;[mod:SHIFT]Summon Voidwalker;Summon Imp",
			["PeaMacro09"] = "#showtooltip\n",
			["PeaMacro03"] = "#showtooltip\n/use [mod:shift,@mouseover,harm,nodead][mod:shift]Curse of Exhaustion;[@mouseover,harm,nodead][@focus,harm,nodead][]Unstable Affliction",
			["PeaMacro12"] = "#showtooltip\n/use [mod:SHIFT]Shadow Bulwark;Unending Resolve",
			["PeaMacro02"] = "#showtooltip\n/use [mod:CTRL] Eye of Kilrogg;[@mouseover,harm,nodead][@focus,harm,nodead][]Shadow Bolt",
			["PeaMacro01"] = "#showtooltip\n/cast [mod:CTRL,@focus,harm,nodead][mod:CTRL]Curse of Weakness;[mod:SHIFT,@mouseover,harm,nodead][mod:SHIFT]Corruption;[@mouseover,harm,nodead][@focus,harm,nodead][]Agony",
			["PeaMacro11"] = "#showtooltip\n/use [mod:CTRL]Create Healthstone;[mod:SHIFT]Healthstone;[@mouseover,harm,nodead][@focus,harm,nodead][]Drain Life",
			["PeaMacro04"] = "#showtooltip\n/use [mod:SHIFT,@mouseover,harm,nodead][mod:SHIFT]Seed of Corruption;[@mouseover,harm,nodead][@focus,harm,nodead][]Malefic Rapture",
			["PeaMacro08"] = "#showtooltip\n",
			["PeaMacro10"] = "#showtooltip\n",
			["PeaMacro05"] = "#showtooltip\n",
			["PeaMacro07"] = "#showtooltip\n/use [mod:ALT]Arcane Pulse;[mod:CTRL,pet:felhunter]Spell Lock;[mod:SHIFT,pet:felhunter,@mouseover,nodead][mod:SHIFT,pet:felhunter]Devour Magic;[@mouseover,harm,nodead][@focus,harm,nodead][]Fear",
		},
		[266] = { -- Demonology
      ["PeaMacro01"] = "#showtooltip\n",
      ["PeaMacro02"] = "#showtooltip\n",
      ["PeaMacro03"] = "#showtooltip\n",
      ["PeaMacro04"] = "#showtooltip\n",
      ["PeaMacro05"] = "#showtooltip\n",
      ["PeaMacro06"] = "#showtooltip\n",
      ["PeaMacro07"] = "#showtooltip\n",
      ["PeaMacro08"] = "#showtooltip\n",
      ["PeaMacro09"] = "#showtooltip\n",
      ["PeaMacro10"] = "#showtooltip\n",
      ["PeaMacro11"] = "#showtooltip\n",
      ["PeaMacro12"] = "#showtooltip\n",
		},
		[267] = { --Destruction
      ["PeaMacro01"] = "#showtooltip\n",
      ["PeaMacro02"] = "#showtooltip\n",
      ["PeaMacro03"] = "#showtooltip\n",
      ["PeaMacro04"] = "#showtooltip\n",
      ["PeaMacro05"] = "#showtooltip\n",
      ["PeaMacro06"] = "#showtooltip\n",
      ["PeaMacro07"] = "#showtooltip\n",
      ["PeaMacro08"] = "#showtooltip\n",
      ["PeaMacro09"] = "#showtooltip\n",
      ["PeaMacro10"] = "#showtooltip\n",
      ["PeaMacro11"] = "#showtooltip\n",
      ["PeaMacro12"] = "#showtooltip\n",
		},
		[1454] = { -- Unassigned
			["PeaMacro01"] = "#showtooltip\n",
			["PeaMacro02"] = "#showtooltip\n",
			["PeaMacro03"] = "#showtooltip\n",
			["PeaMacro04"] = "#showtooltip\n",
			["PeaMacro05"] = "#showtooltip\n",
			["PeaMacro06"] = "#showtooltip\n",
			["PeaMacro07"] = "#showtooltip\n",
			["PeaMacro08"] = "#showtooltip\n",
			["PeaMacro09"] = "#showtooltip\n",
			["PeaMacro10"] = "#showtooltip\n",
			["PeaMacro11"] = "#showtooltip\n",
			["PeaMacro12"] = "#showtooltip\n",
		},
	}
	return macroLib
end
