# https://github.com/BigWigsMods/packager/wiki/GitHub-Actions-workflow
name: Package and Release (BigWigs style)

# we need to let GitHub know _when_ we want to release, typically only when we create a new tag.
# this will target only tags, and not all pushes to the master branch.
# this part can be heavily customized to your liking, like targeting only tags that match a certain word,
# other branches or even pullrequests.
on:
  # Triggers the workflow on tags
  push:
    tags:
      - '**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "release"
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Clone project
        uses: actions/checkout@v2
        with:
          fetch-depth: 50

      # Run for Retail
      - name: Package and release
        uses: BigWigsMods/packager@master

      # Run for Classic
      - name: Package and release for Classic
        uses: BigWigsMods/packager@master
        with:
          args: =g 1.13.5 -w 0
